### ISSUE TITLE
SSE requests are not streamed with immediate flush

### ISSUE THREAD

**Issue by maitredede** [mcluseau/kingress#3]
Hi,

Seams that kingress (1.1.8) always does buffering, even for streaming flows : https://github.com/minio/mc/issues/3296

**Comment by mcluseau** [comment]
Hi,

one of the 2 primary reasons to start kingress was to avoid the buffering-by-default in nginx.

https://github.com/mcluseau/kingress/blob/master/oxy-handler.go#L30

I can will upgrade dependencies just in case, but please have a test to demonstrate the issue.

**Comment by mcluseau** [comment]
On a second look, it seems to depend on the upstream golang issue fixed here

https://go.googlesource.com/go/+/5440bfc2ea8c0a4c78d5161605659c07ea10e37a

1.1.8 was under golang 1.13.0

1.1.9 may have the fix, but I'm pushing 1.1.10 anyway, which is built under golang 1.14.6 (1.15 is in 2 days so that's a bit unfortunate but anyway).

**Comment by mcluseau** [comment]
The SSE case should be detected automatically. There will be a 1.2.0 with a new option related to this after go 1.15.0 is released:
```
  -flush-interval duration
    	forward flush interval.
    	If zero, no periodic flushing is done.
    	A negative value (ie: -1ns) means to flush immediately.
    	Ignored when a response is recognized as a streaming response; for such reponses, writes are flushed immediately. (default 10ms)
```

**Comment by mcluseau** [comment]
golang 1.5.0 took more time than expected but here it is. So is `docker pull mcluseau/kingress:v1.2.0`.

**Comment by mcluseau** [comment]
I will assume that no news is good news...
